/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#dbe1ff',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#0042b3',
          800: '#0057e7',
          900: '#1e3a8a',
        },
        surface: {
          DEFAULT: '#f7f9fb',
          container: '#eceef0',
          'container-low': '#f2f4f6',
          'container-high': '#e6e8ea',
          'container-highest': '#e0e3e5',
          'container-lowest': '#ffffff',
          bright: '#f7f9fb',
          dim: '#d8dadc',
          tint: '#0052dc',
        },
        'on-surface': '#191c1e',
        'on-surface-variant': '#434655',
        'surface-variant': '#e0e3e5',
        'outline': '#737687',
        'outline-variant': '#c3c6d8',
        'on-primary': '#ffffff',
        'primary-fixed': '#dbe1ff',
        'on-primary-fixed': '#00174b',
        'on-primary-fixed-variant': '#003da9',
        secondary: '#47617b',
        'secondary-container': '#c4e0ff',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#49637e',
        tertiary: '#8c2800',
        'tertiary-container': '#b53702',
        'tertiary-fixed': '#ffdbd0',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed-variant': '#842500',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f3',
        'inverse-primary': '#b4c5ff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '1rem',
        full: '9999px',
      },
      fontFamily: {
        sans: ['Be Vietnam Pro', 'system-ui', 'sans-serif'],
        headline: ['Manrope', 'system-ui', 'sans-serif'],
        body: ['Public Sans', 'Be Vietnam Pro', 'system-ui', 'sans-serif'],
        label: ['Public Sans', 'Be Vietnam Pro', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      boxShadow: {
        editorial: '0 12px 40px rgba(25, 28, 30, 0.06)',
        'editorial-lg': '0 20px 60px rgba(25, 28, 30, 0.10)',
      }
    }
  },
  plugins: []
}