spring.application.name=diem-danh

# Spring Neo4j
spring.neo4j.uri=neo4j+s://da0f237f.databases.neo4j.io
spring.neo4j.authentication.username=da0f237f
spring.neo4j.authentication.password=9U717rjMk9y1FbiG8kaPFkBD5kCmxk5iSPz7d7QLJmc
spring.data.neo4j.database=da0f237f
#NEO4J_DATABASE=da0f237f
#AURA_INSTANCEID=da0f237f
#AURA_INSTANCENAME=diem-danh

# Gi?i h?n kích th??c file upload (m?i file)
spring.servlet.multipart.max-file-size=10MB
# Gi?i h?n t?ng kích th??c request
spring.servlet.multipart.max-request-size=20MB

# MinIO
minio.endpoint=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket=diem-danh

# MinIO
app.minio.url=${MINIO_URL:http://localhost:9000}
app.minio.access-key=${MINIO_ACCESS_KEY:minioadmin}
app.minio.secret-key=${MINIO_SECRET_KEY:minioadmin}
app.minio.bucket=${MINIO_BUCKET:socialapp}

# ? FIX: URL công khai ?? browser truy c?p file t? MinIO
# N?u deploy production thì set bi?n môi tr??ng MINIO_PUBLIC_URL=https://your-domain/minio
# N?u local thì ?? tr?ng ? s? dùng app.minio.url
app.minio.public-url=${MINIO_PUBLIC_URL:}

# Server
server.port=8080

# App JWT
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration=86400000
app.jwt.refresh-expiration=604800000
app.jwt.qr-expiration=300000

# Logging
logging.level.com.attendance=DEBUG
logging.level.org.springframework.security=DEBUG